### PR TITLE
Add HTC 10 and fix GT-19305

### PR DESCRIPTION
**Pull request by msfjarvis**
Original PR by @FLooDW, rebased as asked for

### CODE REVIEW

**Comment by msfjarvis** [comment]
Sorry for that merge commit :cry: if you hate those like @xdevs23 does

**Comment by xdevs23** [comment]
Lol y u no remove the merge commit

**Comment by msfjarvis** [comment]
Coz I h8 u lol

**Comment by msfjarvis** [comment]
@corcoran !?!?!?!?!?!?!??!?!?!?

**Comment by corcoran** [comment]
Merges in PRs?!  xdevs23 is right, that's crazy.  I've cherry picked into master and I'm closing this.  Thanks guys!

**Comment by xdevs23** [comment]
@MSF-Jarvis see, that's what I told you :joy:

**Comment by msfjarvis** [comment]
Squash and merge was a thing dude

**Pull request closed without merging**
